### ISSUE TITLE
Reported production panic in `Broker.Append`

### ISSUE THREAD

**Issue by jgraettinger** [LiveRamp/gazette#25]
Was likely during a shutdown of the broker.

```
{"err":"wrong route token\n","level":"warning","msg":"transaction failed (phase one)","time":"2018-01-25T04:36:19Z"}
2018/01/25 04:36:20 http: panic serving 100.105.131.159:42720: send on closed channel
goroutine 2083912 [running]:
net/http.(*conn).serve.func1(0xc42af46780)
    /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0xcc9a40, 0xeb1ff0)
    /usr/local/go/src/runtime/panic.go:491 +0x283
vendor/github.com/LiveRamp/gazette/journal.(*Broker).Append(...)
    /opt/build/src/vendor/github.com/LiveRamp/gazette/journal/broker.go:71
vendor/github.com/LiveRamp/gazette/journal.(*Replica).Append(0xc42b4db1c0, 0xc42030f185, 0x28, 0x7fdcc2aa0310, 0xc42261fc00, 0x14c2980, 0xc42a50ec90, 0xc421441ce0)
    /opt/build/src/vendor/github.com/LiveRamp/gazette/journal/replica.go:58 +0xa6
vendor/github.com/LiveRamp/gazette/gazette.(*Router).Append(0xc420262f20, 0xc42030f185, 0x28, 0x7fdcc2aa0310, 0xc42261fc00, 0x14c2980, 0xc42a50ec90, 0xc421441ce0)
    /opt/build/src/vendor/github.com/LiveRamp/gazette/gazette/router.go:157 +0x4ec
vendor/github.com/LiveRamp/gazette/gazette.(*WriteAPI).Write(0xc42027e310, 0x14c12c0, 0xc4224470a0, 0xc42a512500)
    /opt/build/src/vendor/github.com/LiveRamp/gazette/gazette/write_api.go:36 +0x203
vendor/github.com/LiveRamp/gazette/gazette.(*WriteAPI).Write-fm(0x14c12c0, 0xc4224470a0, 0xc42a512500)
    /opt/build/src/vendor/github.com/LiveRamp/gazette/gazette/write_api.go:21 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42027e340, 0x14c12c0, 0xc4224470a0, 0xc42a512500)
    /usr/local/go/src/net/http/server.go:1918 +0x44
vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420127ea0, 0x14c12c0, 0xc4224470a0, 0xc42a512500)
    /opt/build/src/vendor/github.com/gorilla/mux/mux.go:114 +0xdc
net/http.serverHandler.ServeHTTP(0xc42013ea90, 0x14c12c0, 0xc4224470a0, 0xc427e98700)
    /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc42af46780, 0x14c28c0, 0xc42373b740)
    /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by jgraettinger** [comment]
Closing as won't-fix in favor of gazette2
